# Generated by Django 4.2.20 on 2025-04-05 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mortgage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(800)])),
                ('loan_amount', models.FloatField()),
                ('property_value', models.FloatField()),
                ('annual_income', models.FloatField()),
                ('debt_amount', models.FloatField()),
                ('loan_type', models.CharField(choices=[('fixed', 'Fixed'), ('adjustable', 'Adjustable')], max_length=10)),
                ('property_type', models.CharField(choices=[('single_family', 'Single Family'), ('condo', 'Condo')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit_rating', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
